### ISSUE TITLE
service_provider on ubuntu1604 not 'systemd'

### ISSUE THREAD

**Issue by ghost** [rehanone/puppet-cfssl#18]
Since the service_provider facts contains 'systemd1604' on ubuntu xenial (and surely will contain something else than only 'systemd' on other ubuntu releases) following error occurs:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'File[add-cfssl-conf]' in parameter 'subscribe'`

Maybe line 29 in service.pp should probably be changed to a regex.

original:
`     (...)
      'systemd': {
        file { "remove-${cfssl::service_name}-conf":
        (...)`

should be:
`     (...)
      /^systemd.*$/: {
        file { "remove-${cfssl::service_name}-conf":
        (...)`

**Comment by rehanone** [comment]
I have tested this on a latest xenial vm image and could not find or reproduce this issue. Are you sure you are using the Canonical released copy of xenial image?

**Comment by whocaresDE** [comment]
Sorry, forgot to mention the issue occured inside a linux container. The issue occurs using the ubuntu xenial amd64 lxc image.

**Comment by rehanone** [comment]
Closing this issue as I am intending to archive this repo.
